# 🧠 NumPy Mastery Exercises

> **Goal:** Become comfortable thinking in vectors and matrices instead of Python loops.


# Level 1 — ndarray Basics

## Exercise 1

Create the following arrays:

* 1D array
* 2D array
* 3D array

Print:

* Shape
* Size
* Number of dimensions
* Data type

---

In [1]:
import numpy as np

In [8]:
## 1D Array
array_1 = np.array([1,2,3,4,5])
print("1-D Array")
print("Shape : ", array_1.shape)
print("Size : ", array_1.size)
print("Dimensions : ", array_1.ndim)
print("Type : ", type(array_1))

1-D Array
Shape :  (5,)
Size :  5
Dimensions :  1
Type :  <class 'numpy.ndarray'>


In [9]:
## 2D array
array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2-D Array")
print("Shape : ", array_2.shape)
print("Size : ", array_2.size)
print("Dimensions : ", array_2.ndim)
print("Type : ", type(array_2))

1-D Array
Shape :  (2, 5)
Size :  10
Dimensions :  2
Type :  <class 'numpy.ndarray'>


In [11]:
array_3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print("3-D Array")
print("Shape : ", array_3.shape)
print("Size : ", array_3.size)
print("Dimensions : ", array_3.ndim)
print("Type : ", type(array_3))

3-D Array
Shape :  (2, 2, 5)
Size :  20
Dimensions :  3
Type :  <class 'numpy.ndarray'>


---
## Exercise 2

Convert:

```python
[1,2,3,4,5]
```

into

* int32
* float32
* float64

Observe the difference.


In [22]:
import numpy as np 

arr = np.array([1,2,3,4,5])

print("before : ",arr ,arr.dtype, id(arr))

arr = np.array([1,2,3,4,5],dtype="int32")

print("after :",arr ,arr.dtype, id(arr))

arr = np.array([1,2,3,4,5],dtype="float32")

print("after :",arr ,arr.dtype, id(arr))

arr = np.array([1,2,3,4,5],dtype="float64")

print("after :",arr ,arr.dtype, id(arr))

before :  [1 2 3 4 5] int64 139174465299600
after : [1 2 3 4 5] int32 139174465301328
after : [1. 2. 3. 4. 5.] float32 139174465301904
after : [1. 2. 3. 4. 5.] float64 139174465299600


---

## Exercise 3

Create arrays using:

* np.zeros()
* np.ones()
* np.empty()
* np.arange()
* np.linspace()
* np.eye()
* np.identity()

Print every output.


In [45]:
import numpy as np

print(np.zeros(19))
print(np.ones(19))
print(np.empty(0))
print(np.arange(1,50,2))
print(np.linspace(1,15,5))
print(np.eye(5,dtype="int64"))
print(np.identity(5,dtype="int64"))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 1.   4.5  8.  11.5 15. ]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


| Function        | Purpose                                         | Example Output              |
| --------------- | ----------------------------------------------- | --------------------------- |
| `np.zeros()`    | Fill with 0                                     | `[0. 0. 0.]`                |
| `np.ones()`     | Fill with 1                                     | `[1. 1. 1.]`                |
| `np.empty()`    | Allocate memory without initializing values     | Random/uninitialized values |
| `np.arange()`   | Generate evenly spaced values using a step      | `[0 1 2 3 4]`               |
| `np.linspace()` | Generate a fixed number of evenly spaced values | `[0. 2.5 5. 7.5 10.]`       |
| `np.eye()`      | Identity matrix (square or rectangular)         | Diagonal = 1                |
| `np.identity()` | Identity matrix (square only)                   | Diagonal = 1                |


---

# Level 2 — Indexing

## Exercise 4

Create:

```text
1 2 3
4 5 6
7 8 9
```

Print:

* First row
* Last row
* First column
* Last column
* Middle element
* Last two columns
* First two rows

---

In [55]:
import numpy as np 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("first row : ", arr[0,])
print("last row : ", arr[2,])
print("first column : ", arr[:,0])
print("last column : ", arr[:,2])
print("middle element : ", arr[1,1])
print("last two columns : ", arr[:,1:])
print("first two rows : ", arr[:2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
first row :  [1 2 3]
last row :  [7 8 9]
first column :  [1 4 7]
last column :  [3 6 9]
middle element :  5
last two columns :  [[2 3]
 [5 6]
 [8 9]]
first two rows :  [[1 2 3]
 [4 5 6]]


---
## Exercise 5

Create a 3D array.

Practice accessing:

* First matrix
* Second matrix
* First row
* Last element
* Entire column


In [73]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print("array is :\n", arr_3d)

print("\n\nfirst matrix : ", arr_3d[0,:,:])

print("\n\nsecond matrix : ", arr_3d[1,:,:])

print("\n\nfirst row : ", arr_3d[0,0,:])

print("\n\nlast element : ",arr_3d[1,1,2])

print("\n\nsecond entire column : ",arr_3d[:,:,1])

print("\n\nlast entire column : ",arr_3d[:,:,2])

array is :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


first matrix :  [[1 2 3]
 [4 5 6]]


second matrix :  [[ 7  8  9]
 [10 11 12]]


first row :  [1 2 3]


last element :  12


second entire column :  [[ 2  5]
 [ 8 11]]


last entire column :  [[ 3  6]
 [ 9 12]]


---

# Level 3 — Array Operations

Create:

```python
A = np.array([10,20,30,40,50])
B = np.array([2,4,6,8,10])
```

Perform:

* Addition
* Subtraction
* Multiplication
* Division
* Floor division
* Modulus
* Power


In [78]:
A = np.array([10,20,30,40,50])
B = np.array([2,4,6,8,10])
print("A+B : ", A+B)
print("A-B : ", A-B)
print("A*B : ", A*B)
print("A/B : ", A/B)
print("A//B : ", A//B)
print("A%B : ", A%B)
print("A**B : ", A**B)

A+B :  [12 24 36 48 60]
A-B :  [ 8 16 24 32 40]
A*B :  [ 20  80 180 320 500]
A/B :  [5. 5. 5. 5. 5.]
A//B :  [5 5 5 5 5]
A%B :  [0 0 0 0 0]
A**B :  [              100            160000         729000000     6553600000000
 97656250000000000]


---

## Exercise 6

Without loops calculate

* Square
* Cube
* Square root
* Absolute value

In [84]:
A = np.array([10,20,30,40,50])

print("square : ",A ** 2)
print("cube : ", A ** 3)
print("square root : ", A ** (0.5))
print("absolute value : ", abs(A))

square :  [ 100  400  900 1600 2500]
cube :  [  1000   8000  27000  64000 125000]
square root :  [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
absolute value :  [10 20 30 40 50]


---

# Level 4 — Statistics

Generate

```python
100 random numbers
```

Find

* Mean
* Median
* Standard deviation
* Variance
* Minimum
* Maximum
* Sum


In [109]:
arr = np.linspace(0,1000,100, dtype="int64")
arr = np.random.randint(1,1001, size=100)

# print("Mean : ", arr.mean())
print(arr)
print("Median : ", np.median(arr))
print("Mean : ", np.mean(arr))
print("Standard Deviation : ", np.std(arr))
print("Variance : ", np.var(arr))
print("Minimum : ", np.min(arr))
print("Maximum : ", np.max(arr))
print("Sum : ", sum(arr))

[   0   10   20   30   40   50   60   70   80   90  101  111  121  131
  141  151  161  171  181  191  202  212  222  232  242  252  262  272
  282  292  303  313  323  333  343  353  363  373  383  393  404  414
  424  434  444  454  464  474  484  494  505  515  525  535  545  555
  565  575  585  595  606  616  626  636  646  656  666  676  686  696
  707  717  727  737  747  757  767  777  787  797  808  818  828  838
  848  858  868  878  888  898  909  919  929  939  949  959  969  979
  989 1000]
Median :  499.5
Mean :  499.51
Standard Deviation :  291.53601818643267
Variance :  84993.2499
Minimum :  0
Maximum :  1000
Sum :  49951


---

## Exercise 7

Generate

```python
1000 random integers
```

Find

* Largest 10
* Smallest 10
* Average
* Count of numbers greater than 500
* Count of even numbers

---


In [139]:
arr = np.random.randint(1,10001, size=1000)

print("Array : \n", arr)

largest_10 = np.sort(arr)[-10:]

print("\nLargest 10 : ", largest_10)

smallest_10 = np.sort(arr)[:10]

print("\nSmallest 10 : ", smallest_10)

average = np.average(arr)

print("\nAverage : ", average)

count_of_num_gte_500 = np.sum(arr>500)

print("\nCount of numbers greater than 500 : ", count_of_num_gte_500)

count_even_num = np.sum(arr % 2 == 0 )

print("\nCount of even numbers : ",count_even_num)


Array : 
 [2428 2393 9452 8009 1772 8740 7067 5951  282 1380 7229  243 3919  461
 3259 9835 3176  935 1091  776 4197 7740 7875 1175  418 2258 6516 9238
 1518 7979 2110 4045 8215 8572 1104 1293 6256 4786 4393 6099 7618 9948
 4093 9642 9052 5638 2691  952 6859 7260 1136 1134 5901 8469 9685 8059
 7813 1736 3943 7614 3953 6893  909 5417 2017 5641 3817 4492 3345 2292
 8784 1979 1370 8915 5218 9210 8503 6378 5935 3582 2894 2805 3247 2593
 2476 1382 8991 1066 2042 1321   23 7364 8507 6614 6843 2442  453 2268
 2174 9895 9067 5177 4218  892 9922 4793 4700   13 6960  248 5806 9240
 5664 9318 8333 7330 7527 9830 9428 3369 8724 9248 6925 6093 6912 1801
 9531 2789 6290 4298 1052 2141 3649  482 7157 2392 5275 5456 9277 4664
 6324 9569 6261 1216 4421 7255 9852 6318 1532 9113 3905 9218 1291 7964
 1376 7119 2357 2699 2662 8361  535 5116 9637 3760 7180 1865 1465 4421
 9740 3246 6549 5322 8238 8644  684  200 5341 6142 6364 2918 9496 1447
 9930 6759  489  470 6344 2287 6017 9342 9277  368 7807 4571 5673  

---

# Level 5 — Shape Manipulation

Create

```python
np.arange(1,25)
```

Convert into

* 2×12
* 3×8
* 4×6
* 6×4
* 8×3
* 12×2

---


In [144]:
arr = np.arange(1,25)

arr2 = arr.reshape(2,12)

print("2x12 : \n", arr2)

arr3 = arr.reshape(3,8)

print("3x8 : \n", arr3)

arr4 = arr.reshape(4,6)

print("4x6 : \n", arr4)

arr5 = arr.reshape(6,4)

print("6x4 : \n", arr5)

arr6 = arr.reshape(8,3)

print("8x3 : \n", arr6)

arr7 = arr.reshape(12,2)

print("12x2 : \n", arr7)

2x12 : 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
3x8 : 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
4x6 : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
6x4 : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
8x3 : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
12x2 : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


## Exercise 8

Practice

* reshape()
* flatten()
* ravel()
* transpose()
* T

Write what changes and what remains the same after each operation.

---


In [153]:
arr = np.arange(1,25)

## reshape()

print("Array before reshape() : ", arr)

print("\nAfter reshape to 4x6 : \n\n", arr.reshape(4,6))

## flatten()

arr2 = arr.reshape(4,6)

print("\nArray before flatten() : \n\n", arr2)

print("\nAfter flatten to 4x6 : \n\n", arr2.flatten())

## ravel()

arr2 = arr.reshape(4,6)

print("\nArray before ravel() : \n\n", arr2)


arr3 = np.ravel(arr2)

print("\nAfter ravel to 4x6 : \n\n", arr3,  "\n\nand original one \n", arr3)

Array before reshape() :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

After reshape to 4x6 : 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Array before flatten() : 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

After flatten to 4x6 : 

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Array before ravel() : 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

After ravel to 4x6 : 

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

and original one 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


---

# Level 6 — Boolean Indexing

Create

```python
arr = np.arange(1,51)
```

Find

* Numbers greater than 25
* Even numbers
* Odd numbers
* Multiples of 5
* Numbers between 10 and 30
* Numbers divisible by both 2 and 3

Do not use loops.


In [171]:
arr = np.arange(1,51)

print("Numbers greater than 25 : ", arr[arr>25])
print("Even numbers : ", arr[arr%2==0])
print("Odd numbers : ",arr[arr%2!=0])
print("Multiples of 5 : ", arr[arr%5 == 0])
print("Numbers between 10 and 30 : ", arr[(arr>=10) & (arr<=30)])
print("Numbers divisible by both 2 and 3 : ", arr[(arr%2 == 0) & (arr%3 == 0)])

Numbers greater than 25 :  [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]
Even numbers :  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Odd numbers :  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Multiples of 5 :  [ 5 10 15 20 25 30 35 40 45 50]
Numbers between 10 and 30 :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Numbers divisible by both 2 and 3 :  [ 6 12 18 24 30 36 42 48]


---

# Level 7 — Broadcasting

Create

```python
A = np.arange(9).reshape(3,3)
```

Perform

* A + 10
* A * 5
* A + row vector
* A + column vector

Observe broadcasting.

Explain in your own words why broadcasting works.


In [176]:
A = np.arange(9).reshape(3,3)
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A is \n", A)
print("A + 10", A + 10)
print("A * 5", A * 5)
print("A + row vector [1,2,3]\n", A + B[0])
print("A + column vector \n", A + B[:,2])

A is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A + 10 [[10 11 12]
 [13 14 15]
 [16 17 18]]
A * 5 [[ 0  5 10]
 [15 20 25]
 [30 35 40]]
A + row vector [1,2,3]
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
A + column vector 
 [[ 3  7 11]
 [ 6 10 14]
 [ 9 13 17]]


---

# Level 8 — Random Module

Generate

* Random floats
* Random integers
* Random matrix
* Random binary matrix

Set

```python
np.random.seed(42)
```

Generate the same numbers twice.

Explain why reproducibility is important in Machine Learning.



In [191]:
from numpy import random

print(random.rand(5))
print(random.randint(5))
print(random.rand(3, 4))
print(random.randint(0,2,size=(3,4)))
random.seed(78)
print(random.randint(1, 100)) 

[0.88733303 0.5733576  0.59658201 0.32560075 0.76062093]
3
[[0.5663575  0.75155307 0.56857494 0.43557206]
 [0.95183206 0.79763247 0.67652832 0.4762874 ]
 [0.82396207 0.90718803 0.45028405 0.88519175]]
[[0 1 0 0]
 [1 0 1 0]
 [0 0 0 0]]
70


---

# Level 9 — Mini AI Exercises

## Exercise 1

Normalize

```text
[10,20,30,40,50]
```

using

```text
(x-min)/(max-min)
```



In [195]:
x = np.array([10,20,30,40,50])
print((x-np.min(x))/(np.max(x)-np.min(x)))

[0.   0.25 0.5  0.75 1.  ]


---

## Exercise 2

Standardize

```text
[10,20,30,40,50]
```

using

```text
(x-mean)/std
```


In [196]:
x = np.array([10,20,30,40,50])
print((x-np.mean(x))/np.std(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


---

## Exercise 3

Generate

```python
1000
```

random student marks.

Find

* Students above 90
* Students below 35
* Average marks
* Top 20 students

In [209]:
marks = random.randint(0,100,1000)
print("Students above 90 : ", sum(marks>90))
print("Students below 35 : ", sum(marks<=35))
print("Average marks : ", np.average(marks))
print("Top 20 students : ", np.sort(marks)[-20::][::-1])

Students above 90 :  99
Students below 35 :  364
Average marks :  49.583
Top 20 students :  [99 99 99 99 99 99 99 99 99 99 99 99 99 98 98 98 98 98 98 98]


---

## Exercise 4

Generate a fake image

```python
(224,224,3)
```

Print

* Shape
* Size
* Dimensions

Explain why images are stored this way.



In [214]:
image = np.random.rand(224,224,3)
print("Shape : ",image.shape)
print("Size : ",image.size)
print("Dimensions : ",image.ndim)

Shape :  (224, 224, 3)
Size :  150528
Dimensions :  3


---

## Exercise 5

Generate

```python
1000 samples
```

Each sample should have

```text
5 features
```

Print

* Shape
* Mean of each feature
* Standard deviation of each feature

This is similar to preparing data before training an ML model.

---


In [217]:
import numpy as np

data = np.random.randint(1, 101, size=(1000, 5))
print(data.shape)
print([np.mean(data[:,i]) for i in range(5)])
print([np.std(data[:,i]) for i in range(5)])

(1000, 5)
[np.float64(50.56), np.float64(51.497), np.float64(49.734), np.float64(51.002), np.float64(50.685)]
[np.float64(28.66371225085823), np.float64(29.478025561424563), np.float64(29.54320977822146), np.float64(29.34617515111637), np.float64(29.71507656056097)]


---

# Level 11 — Matrix Operations

Create two matrices.

Practice

* Matrix addition
* Matrix subtraction
* Matrix multiplication
* Element-wise multiplication
* Matrix transpose


In [223]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Matrix addition : ", A + B)
print("Matrix subtraction : ", A - B)
print("or Matrix multiplication : ", A @ B)
print("or Matrix multiplication : ", np.matmul(A, B))
print("or Matrix multiplication : ", np.dot(A, B))
print("Element-wise multiplication : ", A*B)
print("Matrix transpose : ", np.transpose(A))

Matrix addition :  [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix subtraction :  [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
or Matrix multiplication :  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
or Matrix multiplication :  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
or Matrix multiplication :  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise multiplication :  [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix transpose :  [[1 4 7]
 [2 5 8]
 [3 6 9]]


---

## Exercise

Calculate

* Row sums
* Column sums
* Diagonal sum

without loops.


In [225]:
print("Sum of first row : ",np.sum(A[0,:]))
print("Sum of Middle row : ", np.sum(A[1,:]))
print("Sum of Last row : ", np.sum(A[2,:]))
print("Sum of first Column : ",np.sum(A[:,0]))
print("Sum of Middle Column : ", np.sum(A[:,1]))
print("Sum of Last Column : ", np.sum(A[:,2]))

Sum of first row :  6
Sum of Middle row :  15
Sum of Last row :  24
Sum of first Column :  12
Sum of Middle Column :  15
Sum of Last Column :  18


---

# Final Challenge 🏆

Without watching any tutorial, build a small **Student Analytics System** using only NumPy.

The program should:

* Generate marks for 500 students.
* Calculate average, highest, and lowest marks.
* Count passed and failed students.
* Find the top 10 students.
* Normalize marks.
* Standardize marks.
* Display grade distribution (A, B, C, D, F).
* Calculate the pass percentage.conditions = [
    marks >= 90,
    marks >= 80,
    marks >= 70,
    marks >= 50
]

choices = ["A", "B", "C", "D"]

grades = np.select(conditions, choices, default="F")

* Print all results without using Python loops wherever possible.

---


In [229]:
## 1 Generate marks for 500 students.

marks = random.randint(0,101,500)

print("Marks : ", marks)

## 2 Calculate average, highest, and lowest marks

print("Average of marks : ", np.average(marks))

print("Highest Marks : ", np.sort(marks)[-1])

print("Lowest Marks : ", np.sort(marks)[1])

## 3 Count passed and failed students.

print("Passed students : ", np.sum(marks>=36))

print("Failed students : ", np.sum(marks<36))

print("The top 10 students : ", np.sort(marks)[-10:][-1])

print("Normalized Marks : ", (marks - np.min(marks))/(np.max(marks)-np.min(marks)))

print("Standardize marks : ", (marks - np.mean(marks))/(np.std(marks)))


conditions = [
    marks >= 90,
    marks >= 80,
    marks >= 70,
    marks >= 50
]

choices = ["A", "B", "C", "D"]

grades = np.select(conditions, choices, default="F")

print("grade distribution : ", grades)

print("The pass percentage : ", np.sum(marks>=36)*100/500)

Marks :  [  7  89  59  77  13  76  81  69  57  35  28  91  46   2  32  93   8  65
  69  45  70  98  30  91  93  65  96  81  45  20  87  63  36  84  52  40
 100  31  82  55  48  71  58  80  66  56  19   5  22  40  29  52  86  76
  32  68  57  35  90  88  29  44  67  24  69  77  50   3  86  56  91  18
  35  58  55  72  37  22  11  72   8  90  20  67   9  38  67   4  10  22
   6  80   4  99  40  72   4   1  79  20  12  92 100  10  80  97  11  66
  35  95  37  80  69  73   8  18  58  75  92  56  33  60  71  72  38  63
   3  38  92  87  81  95  47  32  57  38  92  20  99  42  30  95  33  74
  24  84  25  31  42  98  88  17   2   0  81  92  90  45  69  98  95  69
  74  93  10  23  82  98  80  95  46  45  30  65  15  51  88  30  44  75
  27  36  31  45  46   1  22  99  89   0  66  39  98  80  99  55  55   2
  18  90  51  48  10  65  92  30   4  24   0  22  15   2  23  99  26  14
  96  53  42  24   9  51  82  31  49  48  94  39  97  85  16  73  32  28
   0  63  70  66  27  83  62  17  11  39  